export const UPDATE_ESTIMATION_SUCCESS = "UPDATE_ESTIMATION_SUCCESS";
export const UPDATE_ESTIMATION_FAIL = "UPDATE_ESTIMATION_FAIL";

export const RESET_ESTIMATION_SUCCESS = "RESET_ESTIMATION_SUCCESS";
export const RESET_ESTIMATION_FAIL = "RESET_ESTIMATION_FAIL";
