// PROJECTS
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS";
export const GET_ALL_PROJECTS_FAIL = "GET_ALL_PROJECTS_FAIL";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL";
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
export const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

// CONTRACTS
export const CREATE_CONTRACT_SUCCESS = "CREATE_CONTRACT_SUCCESS";
export const CREATE_CONTRACT_FAIL = "CREATE_CONTRACT_FAIL";
export const SEND_CONTRACT_SUCCESS = "SEND_CONTRACT_SUCCESS";
export const SEND_CONTRACT_FAIL = "SEND_CONTRACT_FAIL";

// OFFERS
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAIL = "CREATE_OFFER_FAIL";
export const SEND_OFFER_SUCCESS = "SEND_OFFER_SUCCESS";
export const SEND_OFFER_FAIL = "SEND_OFFER_FAIL";

// PAYMENTS
export const EXECUTE_PAYMENT_SUCCESS = "EXECUTE_PAYMENT_SUCCESS";
export const EXECUTE_PAYMENT_FAIL = "EXECUTE_PAYMENT_FAIL";

// PRICE LIST
export const GET_PRICE_LIST_SUCCESS = "GET_PRICE_LIST_SUCCESS";
export const GET_PRICE_LIST_FAIL = "GET_PRICE_LIST_FAIL";
export const UPDATE_PRICE_LIST_SUCCESS = "UPDATE_PRICE_LIST_SUCCESS";
export const UPDATE_PRICE_LIST_FAIL = "UPDATE_PRICE_LIST_FAIL";
export const CREATE_ITEM_PRICE_LIST_SUCCESS = "CREATE_ITEM_PRICE_LIST_SUCCESS";
export const CREATE_ITEM_PRICE_LIST_FAIL = "CREATE_ITEM_PRICE_LIST_FAIL";
export const DELETE_ITEM_PRICE_LIST_SUCCESS = "DELETE_ITEM_PRICE_LIST_SUCCESS";
export const DELETE_ITEM_PRICE_LIST_FAIL = "DELETE_ITEM_PRICE_LIST_FAIL";
